function test_keyboard_gui()
    % Test GUI for keyboard input that avoids using command window output
    % Optimized for SSH+X11 forwarding where command window output may be problematic
    
    % Create figure with white background
    fig = figure('Color', 'white', ...
                'Position', [100, 100, 500, 400], ...
                'Name', 'SSH Keyboard Test', ...
                'NumberTitle', 'off', ...
                'MenuBar', 'none');
    
    % Set up axes to contain text
    ax = axes('Parent', fig, ...
             'Position', [0.1, 0.1, 0.8, 0.8], ...
             'XTick', [], 'YTick', [], ...
             'XLim', [0 1], 'YLim', [0 1], ...
             'Box', 'on');
    
    % Create instruction text
    text(0.5, 0.5, 'Press any key to begin test', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 14, ...
        'Parent', ax);
    
    % Initialize user data
    fig.UserData = struct();
    
    % Set up key press callback
    fig.KeyPressFcn = @keypress_gui_callback;
    
    % Wait until figure is closed
    uiwait(fig);
end 